export const projects = [
  {
    id: 1,
    title: "Pretium",
    description: "Take a Picture and Scan. Get Price Estimates.",
    tech: ["React Native", "Search Engine"],
    link: "https://github.com/whiteowly/Pretium",
    image: "/src/assets/pretium.png",
    status: "",
  },
  {
    id: 2,
    title: "Penpad-Mobile",
    description: "A simple To-Do app with shared task management features.",
    tech: ["React Native", "Firebase", "Firestore"],
    link: "https://github.com/whiteowly/Penpad-Mobile",
    image: "/src/assets/PenpadPhone.jpg",
    status: "",
  },
  {
    id: 3,
    title: "Penpad-PC",
    description: "Desktop app for monitoring your daily life.",
    tech: ["React", "Firebase", "Firestore"],
    link: "https://github.com/whiteowly/penpad",
    image: "/src/assets/penpadPC.jpg",
    status: "In Progress",
  },
   {
    id: 4,
    title: "Secret Santa Telegram Bot",
    description: "A Telegram bot that organizes Secret Santa gift exchanges.",
    tech: ["Python", "SQLite", "Telegram Bot API"],
    link: "https://github.com/whiteowly/Secret-Santa",
    image: "/src/assets/secret-santa.jpg",
    status: "",
  },
   {
    id: 5,
    title: "Maphia",
    description: "A mobile game that organizes mafia games among friends.",
    tech: ["React Native", "BetterAuth", "Node.js"],
    link: "https://github.com/whiteowly/Maphia",
    image: "/src/assets/maphia.png",
    status: "In Progress",
  },
   {
    id: 6,
    title: "Checkers Game",
    description: "Chceckers game with UI",
    tech: ["C++", "Raylib"],
    link: "https://github.com/whiteowly/Checkers",
    image: "/src/assets/checkers.jpg",
    status: "",
  },
   {
    id: 7,
    title: "Guesthouse Management System",
    description: "Guesthouse frontdesk management system",
    tech: ["C#", "MySQL"],
    link: "https://github.com/whiteowly/Guesthouse-Management-System",
    image: "/src/assets/Guesthouse.jpg",
    status: "",
  },
];

// Provide default export as a fallback for consumers importing the module differently
export default projects;
