// src/services/token.service.ts
import jwt from 'jsonwebtoken';
import { User } from '@prisma/client'; // Import the type generated by Prisma
import { IJwtPayload } from '../types/auth.types';

const JWT_SECRET = process.env.JWT_SECRET!;
const EXPIRATION = '15m'; 

export function generateAccessToken(user: User): string {
    // We map the full User object to our smaller, specific payload interface
    const payload: IJwtPayload = {
        sub: user.id, 
        username: user.username,
        universe_xp: user.universe_xp,
        currency_balance: user.currency_balance,
    };

    const token = jwt.sign(
        payload, 
        JWT_SECRET,
        { expiresIn: EXPIRATION }
    );

    return token;
}